// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY09APXLVHB0OSn70P16htDBq4drE9kvo',
    appId: '1:246804869698:web:1c3f9c4af27a3e17bd73db',
    messagingSenderId: '246804869698',
    projectId: 'valetapp-b84e1',
    authDomain: 'valetapp-b84e1.firebaseapp.com',
    storageBucket: 'valetapp-b84e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFMHS5X0PqFDbfhVuKpXmYUaw7QjN1kko',
    appId: '1:246804869698:android:20511a2bc9901a72bd73db',
    messagingSenderId: '246804869698',
    projectId: 'valetapp-b84e1',
    storageBucket: 'valetapp-b84e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflMqTjjT3ioYwHYfcPX4UnH4jJjZv8yY',
    appId: '1:246804869698:ios:df632edebdd07a26bd73db',
    messagingSenderId: '246804869698',
    projectId: 'valetapp-b84e1',
    storageBucket: 'valetapp-b84e1.appspot.com',
    iosClientId: '246804869698-osgtounarqt1vusogpq9d0542tln2upu.apps.googleusercontent.com',
    iosBundleId: 'com.example.homePage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDflMqTjjT3ioYwHYfcPX4UnH4jJjZv8yY',
    appId: '1:246804869698:ios:df632edebdd07a26bd73db',
    messagingSenderId: '246804869698',
    projectId: 'valetapp-b84e1',
    storageBucket: 'valetapp-b84e1.appspot.com',
    iosClientId: '246804869698-osgtounarqt1vusogpq9d0542tln2upu.apps.googleusercontent.com',
    iosBundleId: 'com.example.homePage',
  );
}
